EVALUATE
SUMMARIZECOLUMNS(
	//Columns
	'Dim - Calendar'[Fiscal Year],
	'Dim - Calendar'[Fiscal Quarter],
	'Dim - Calendar'[Fiscal Week],
	'Hier - Channel'[Region Desc],
	'Hier - Channel'[SubRegion Desc],
	'Hier - Product'[Product Type],
	'Hier - Product'[Product Group],
	'Hier - Product'[LOB],
	
	//Filters
    FILTER (
		VALUES ( 'Dim - Calendar'[Fiscal Quarter Lag] ),
		( 'Dim - Calendar'[Fiscal Quarter Lag] >= -7 )
    ),
    FILTER (
		VALUES ( 'Dim - Calendar'[Fiscal Week Lag] ),
		( 'Dim - Calendar'[Fiscal Week Lag] <= -1 )
    ),
    FILTER (
		VALUES ( 'Hier - Agent'[Category Name] ),
		( 'Hier - Agent'[Category Name] = "Tech Support" )
    ),
    FILTER (
		VALUES ( 'Hier - Agent'[Department Name] ),
		( 'Hier - Agent'[Department Name]  <> "TS-DOSD" )
    ),
    FILTER (
		VALUES ( 'Hier - Product'[Product Type] ),
		( 'Hier - Product'[Product Type] = "Enterprise Solution Group PBU" )
    ),
    FILTER (
    	VALUES ('Fact - CE Responses'[CE Warranty Status] ),
    	( 'Fact - CE Responses'[CE Warranty Status] <> "OOW" )
    ),
    FILTER (
    	VALUES ('Fact - CE Responses'[Response Status] ),
    	( 'Fact - CE Responses'[Response Status] = "Completed" || 'Fact - CE Responses'[Response Status] = "CompletedSurvey" )
    ),
    FILTER (
    	VALUES ( 'Fact - CE Disposition'[Survey ID] ),
    	( 'Fact - CE Disposition'[Survey ID] <> "3076" )
	),
    FILTER (
    	VALUES ( 'Fact - Case SFDC'[SFDC Case Type] ),
    	( 'Fact - Case SFDC'[SFDC Case Type] <> "Internal Case" )
	),
    

	//Expressions
	//"CSAT",[Universal Sat %],
	"CSAT_NUM",[Universal Satisfied Responses],
	"CSAT_DENOM",[Universal Responses],
	//"RDR",[Repeat Dispatch 7 Day Lag %],
	"RDR_NUM",[Repeat Dispatch 7 day Numerator],
	"RDR_DENOM",[Repeat Dispatch Denominator],
	//"TTC",[TTC – SFDC + DELTA],
	"TTC_NUM",CALCULATE(
					    SUM('Fact - Case SFDC'[Time to Complete])/86400
					    , 'Fact - Case SFDC'[Quick Contact Flag]<>"Y"
					    , TREATAS(VALUES('Dim - Calendar'[DATE]),'Fact - Case SFDC'[Complete Date])
					    , TREATAS(VALUES('Hier - Agent'[Agent Key]),'Fact - Case SFDC'[Agent_Owner_Key_ClosedDate])
					  )
					  + CALCULATE(
					    SUM('Fact - SR'[CASE AGE])
					    , 'Fact - SR'[SFDC Exlusion Flag]=0
					    , TREATAS(VALUES('Dim - Calendar'[DATE]),'Fact - SR'[Activity Close Date])
					    , TREATAS(VALUES('Hier - Agent'[Agent Key]),'Fact - SR'[OwnerKey_closedate])
					  ),
	"TTC_DENOM",[Cases Completed (Owner) SFDC + DELTA],
	
	"CSAT_NUM_PRO",CALCULATE([Universal Satisfied Responses],'Hier - Monarch Entiltlement'[Offer Level] = "ProSupport" || 'Hier - Monarch Entiltlement'[Offer Level] = "ProSupport Plus"),
	"CSAT_DENOM_PRO",CALCULATE([Universal Responses],'Hier - Monarch Entiltlement'[Offer Level] = "ProSupport" || 'Hier - Monarch Entiltlement'[Offer Level] = "ProSupport Plus"),
	"CSAT_NUM_BASIC",CALCULATE([Universal Satisfied Responses],'Hier - Monarch Entiltlement'[Offer Level] = "Basic" || 'Hier - Monarch Entiltlement'[Offer Level] = BLANK() || 'Hier - Monarch Entiltlement'[Offer Level] = "NA"),
	"CSAT_DENOM_BASIC",CALCULATE([Universal Responses],'Hier - Monarch Entiltlement'[Offer Level] = "Basic" || 'Hier - Monarch Entiltlement'[Offer Level] = BLANK() || 'Hier - Monarch Entiltlement'[Offer Level] = "NA"),

	"DSAT_NUM_PRO",CALCULATE([Universal Dissatisfied Responses],'Hier - Monarch Entiltlement'[Offer Level] = "ProSupport" || 'Hier - Monarch Entiltlement'[Offer Level] = "ProSupport Plus"),
	"DSAT_DENOM_PRO",CALCULATE([Universal Responses],'Hier - Monarch Entiltlement'[Offer Level] = "ProSupport" || 'Hier - Monarch Entiltlement'[Offer Level] = "ProSupport Plus"),
	"DSAT_NUM_BASIC",CALCULATE([Universal Dissatisfied Responses],'Hier - Monarch Entiltlement'[Offer Level] = "Basic" || 'Hier - Monarch Entiltlement'[Offer Level] = BLANK() || 'Hier - Monarch Entiltlement'[Offer Level] = "NA"),
	"DSAT_DENOM_BASIC",CALCULATE([Universal Responses],'Hier - Monarch Entiltlement'[Offer Level] = "Basic" || 'Hier - Monarch Entiltlement'[Offer Level] = BLANK() || 'Hier - Monarch Entiltlement'[Offer Level] = "NA")
//SUMMARIZECOLUMNS
)